---
- name: Install necessary zsh homebrew packages
  become: false
  homebrew:
    name: ["zsh"]
    state: present

- name: Check for .oh-my-zsh exists
  become: false
  stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: ohmyzsh_folder

- name: Install OhMyZsh
  become: false
  shell: |
    sh -c "$(curl -fsSL {{ ohmyzsh_install_url }})"
  when: not ohmyzsh_folder.stat.exists

- name: Check for powerlevel10k exists
  become: false
  stat:
    path: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: powerlevel10k_folder

- name: Install powerlevel10k theme
  become: false
  git:
    repo: "{{ powerlevel10k_theme_url }}"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ powerlevel10k_theme_version }}"
  when: not powerlevel10k_folder.stat.exists

- name: Install nerd fonts 1/2
  become: false
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install nerd fonts 2/2
  become: false
  homebrew_cask:
    name: ["font-hack-nerd-font", "font-fira-code-nerd-font", "font-fira-mono-nerd-font"]
    state: present

- name: Copy .zshrc file
  become: false
  copy:
    src: "dotfiles/.zshrc"
    dest: "{{ home_dir }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Copy .p10k.zsh file
  become: false
  copy:
    src: "dotfiles/.p10k.zsh"
    dest: "{{ home_dir }}/.p10k.zsh"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Copy .tmux.conf file
  become: false
  copy:
    src: "dotfiles/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Set default shell
  become: true
  user:
    name: "{{ username }}"
    shell: /bin/zsh  