---
- name: Add VSCode Gatekeeper Exception
  command: "spctl --add /Applications/Visual\ Studio\ Code.app/"
  changed_when: true
  ignore_errors: true
  become: true

- name: Install Visual Studio Code extensions
  command: code --install-extension {{ item.id | default(item) }}
  with_items: "{{ vscode_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"