---
- name: Install necessary zsh homebrew packages
  homebrew:
    name: ["zsh"]
    state: present

- name: Check for .oh-my-zsh exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_folder

- name: Install OhMyZsh
  shell: |
    sh -c "$(curl -fsSL {{ ohmyzsh_install_url }})"
  when: not ohmyzsh_folder.stat.exists

- name: Check for powerlevel10k exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: powerlevel10k_folder

- name: Install powerlevel10k theme
  git:
    repo: "{{ powerlevel10k_theme_url }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ powerlevel10k_theme_version }}"
  when: not powerlevel10k_folder.stat.exists

- name: Install nerd fonts 1/2
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install nerd fonts 2/2
  homebrew_cask:
    name: ["font-hack-nerd-font", "font-fira-code-nerd-font", "font-fira-mono-nerd-font"]
    state: present

- name: Copy .zshrc file
  copy:
    src: "zsh/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Copy .p10k.zsh file
  copy:
    src: "zsh/.p10k.zsh"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Copy .tmux.conf file
  copy:
    src: "zsh/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0644

- name: Set default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: true

  