---
vscode_extensions:
  - { name: "Solarized", id: "ryanolsonx.solarized" }
  - { name: "Rainbow CSV", id: "mechatroner.rainbow-csv" }
  - { name: "JSON Tools", id: "eriklynd.json-tools" }
  - { name: "Markdown All in One", id: "yzhang.markdown-all-in-one" }
  - { name: "todo-txt", id: "rarnoldmobile.todo-txt" }
  - { name: "YAML", id: "redhat.vscode-yaml" }
  - { name: "Ansible", id: "redhat.ansible" }
  - { name: "vscode-pandoc", id: "DougFinke.vscode-pandoc" }
  - { name: "Docker", id: "ms-azuretools.vscode-docker" }
  - { name: "PlantUML", id: "jebbs.plantuml" }
  - { name: "Prettier - Code formatter", id: "esbenp.prettier-vscode" }