---
homebrew_packages_to_install:
  - git
  - ansible
  - terraform
  - wget
  - lsd
  - htop
  - bat
  - tree
  - fzf
  - tmux
  - python@3.10
  - neofetch
  - ssh-copy-id

homebrew_casks_to_install:
  - iterm2
  - rectangle
  - visual-studio-code
  - keka
  - iina
  - insomnia
  - keepassxc
  - google-chrome
  - discord
  - raspberry-pi-imager